server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /catalog-services/api
spring:
  webflux:
    base-path: /catalog-services/api
  application:
    name: catalog-services
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}