server:
  port: 9100
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/afcarrera/microservices-spring_boot-jpa.git
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          search-paths:
            - config-data
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}

